#!/bin/bash

# Get library to use functions
source library
requirement=(apache2-utils)

isSet_hostname # Solve the hostname warning
isExist_package # Check pacages and install them

# Variables for default AB setting
num_pattern='^[0-9]+$'
num_request=10
target_server=127.0.0.1:80
isCorrect=-1
pool=1

# Print the number of HTTP request messages generated by this script
if [[ $1 == "-h"  ]]; then
  echo "[Help] Please enter the command: ./test_http.sh {number of requests} {target_server}"
  echo "[Help] example: ./test_http.sh 100 127.0.0.1:8080"
else
  if [[ ! -z $1 ]]; then
    if [[ $1 =~ $num_pattern ]]; then
      num_request=$1
      echo "[Log] The number of http request messages: $num_request"

			if [[ $num_request -lt 10 ]]; then
				pool=1
			else
				pool=$((num_request/10))
			fi

      isCorrect=1
    else
      echo "[Error] Please enter a correct number"
    fi
  else
    echo "[Log] The number of http request messages: $num_request (default value)"
    isCorrect=1
  fi

# Print the target server of HTTP request messages
  if [[ ! -z $2 ]]; then
    target_server=$2
    echo "[Log] Send HTTP request messages to $target_server"
  else
    echo "[Log] Send HTTP request messages to $target_server (default value)"
  fi

# Generate and send HTTP request messages to the target server
  if [[ $isCorrect -lt 0 ]]; then
    echo "[Error] please check your input values again"
  else
    echo "[Log] ready to send http request messages"
    ab -n $num_request -c $pool $target_server/
  fi
fi
